### ISSUE TITLE
Feature documentation: Implement support for EIP-1559 transactions 

### ISSUE THREAD

**Issue by bgravenorst** [Consensys/doc.web3signer#166] opened 2023-04-26 02:08 UTC
Add support for EIP-1559 transactions.

See: https://github.com/ConsenSys/web3signer/issues/769

Perhaps we should bring over EthSigner's "Make transactions" content and update it for 1559.

**Comment by alexandratran** [comment] 2023-08-14 19:29
duplicate of #196

**Closed by alexandratran** 2023-08-14 19:29 UTC
